name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: The system should...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you thought about?
      placeholder: I also considered...
  
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Any examples from other projects or systems?
      placeholder: Similar to how X does Y...
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am willing to help implement this
          required: false
